config/routes.rb
Rails.application.routes.draw do
  get 'events/new'

  get 'sessions/new'

  get 'workers/index'
  get 'workers/show'

  get 'users/new'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'personnel' => 'workers#index'
  get 'add-personnel' => 'workers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :workers
  resources :events

  root 'static_pages#home'

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :pictures
	belongs_to :event
	has_attached_file :avatar, storage: :imgur
end

app/models/event.rb
class Event < ActiveRecord::Base
has_one :album
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :album
	has_attached_file :avatar, storage: :imgur
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length:{ minimum:6 }, presence: true
end

app/models/worker.rb
class Worker < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
	validates :bio, presence: true
	validates :role, presence: true
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
 #  def fetch_online_status(sourceStream)
	# 	stream = open('https://api.twitch.tv/kraken/streams/' + sourceStream)
	# 	response_body = stream.read[559,441]
	# 	if response_body.nil?
	# 		 false
	# 	else
	# 		 true
	# 	end
	# end
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  # protect_from_forgery with: :exception
  # include SessionsHelper
  # include ApplicationHelper
  # @scgg = fetch_online_status("smartcastgg")
  # @scgg2 = fetch_online_status("smartcastgg2")
  # @mecha = fetch_online_status("ikkou901")
  # @will = fetch_online_status("promech")
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end
  def index
  	@elist = Event.all()
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@worker = Worker.new
  end
  def create
  	render 'new'
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      @worker = Worker.new
      redirect_to '/add-personnel'
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def about
  end
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.all
  end
  def index
  	@user = User.all
  end
  def new
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  #   before_action :require_login
  # skip_before_action :require_login, :except => [:edit,:new] 


  
  def index
  	@worker = Worker.all
  end
  def show
  	@worker = Worker.all
  end
  def new
  	if logged_in?
  		@worker = Worker.new
  	else
  		redirect_to '/home'
  	end
  end
  def create
    @worker = Worker.new(worker_params)    # Not the final implementation!
    if @worker.save
      redirect_to '/personnel' # Handle a successful save.
    else
      render 'new'
  	end
  end
  def edit
    @worker = Worker.find(params[:id])
  end
	#Private functions that allow extra functionalities.  
   private
   	def worker_params
  	 	params.require(:worker).permit(:name, :email, :avatar,:bio, :role, :twitter)
  	end
  def require_login
    unless current_user
      redirect_to '/home'
  end

end
end

app/helpers/application_helper.rb
module ApplicationHelper
	require 'open-uri'
	def full_title(page_title='')
		base_title = "SmartcastGG"
		if page_title.empty?
			base_title
		else
			page_title + "|" + "SmartcastGG"
		end
	end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/layouts/_sidebar.html.erb
<div class= "col-md-3 sidebar">
<iframe class="Calendar" src="https://www.google.com/calendar/embed?src=en.pr%23holiday%40group.v.calendar.google.com&ctz=America/Anguilla" style="border: 0" width="700px" height="300px" frameborder="0" scrolling="no"></iframe>
</div>

app/views/layouts/_stream.html.erb
<iframe src="http://player.twitch.tv/?channel=smartcastgg" frameborder="0" scrolling="no" height="378" width="80%"></iframe><a href="http://www.twitch.tv/smartcastgg?tt_medium=live_embed&tt_content=text_link" style="padding:2px 0px 4px; display:block; width:345px; font-weight:normal; font-size:10px;text-decoration:underline;"></a>

app/views/layouts/_twitter.html.erb
		<a class="twitter-timeline" width="530" height="400" href="https://twitter.com/JomSnow901/lists/scgg" data-widget-id="647618758702440448"></a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/_yt.html.erb
<iframe class="YoutubeVideo" width="100%" height="400px" src="https://www.youtube.com/embed/videoseries?list=PL6YZkeWa4hQV73_NHf3gMaJsStPDZU4nY" frameborder="0" allowfullscreen></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <head>
 <%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

  </head>
  <body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

     <%= image_tag("SCGGnoText.png", alt: "SCGGLogoNoText", id:"logoNavBar") %>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:action] == 'home' %>"><%= link_to "Home", home_path %></li> 
        <!-- <li class="<%= 'active' if params[:controller] == 'workers' %>"><%= link_to "Personnel", '/personnel' %></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Streams <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="http://www.twitch.tv/smartcastgg">SmartcastGG <%if @scgg %><strong>Live!</strong><%end%> </a></li>
            <li><a href="http://www.twitch.tv/smartcastgg2">SmartcastGG2 <%if @scgg2 %><strong>Live!</strong><%end%> </a></li>
            <li><a href="http://www.twitch.tv/ikkou901">Mecha Albizu <%if @mecha %><strong>Live!</strong><%end%> </a></li>
            <li><a href="http://secure.twitch.tv/promech">Promech <%if @will %><strong>Live!</strong><%end%> </a></li>
            <!-- <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
        <!-- <li class="<%= 'active' if params[:controller] == 'events' %>"><%= link_to "Events", controller: "events", action: "index" %></li> -->
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="bodyWrapper row">
<%= yield %>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>
      This is the about page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="main">


<h1>SmartcastGG</h1>
<div id="ytdiv">

		<%= render 'layouts/stream' %>
	
</div>


	<div class="row services">
	<h1>Services</h1>
		<div class="col-md-4 service" id="service1div">
				<div id="iconContainer1">
				<p><h3>Streaming</h3></p>
					<i class="fa fa-video-camera fa-5x" id="service1"></i>
				</div>
		<div id="Information1" >
		<p>We offer full casting services for your event. Streamed in full HD and complete with graphics for your event. Need on site help with the setup of your stream? no problem. SCGG has the hardware to stream just about every esport out there. With SmartcastGG streaming your event, your event will come to life. </p>
		</div>

				
		</div>
		<div class="col-md-4 service row" id="service2div">
			<div id="iconContainer2">
					<p><h3>Casting</h3></p>
					<i class="fa fa-microphone fa-5x" id="service2"></i>
			</div>
			<div id="Information2">
			<p>Imagine having your Esports event having live commentary by people who know the game being played at your event. With SmartcastGG, you'll have access to a full team of people who not only know the game inside out, but also analyze plays that were made and are capable of exciting a crowd.</p>
			</div>
		</div>
		<div class="col-md-4 service row" id="service3div">
				<div id="iconContainer3">
					<p><h3>Hosting</h3></p>
					<i class="fa fa-users fa-5x" id="service3"></i>
				</div>
					<div id="Information3">
					<p>Have an idea for an Esports event but don't quite have the resources to properly host it? At SmartcastGG we count on a team of people that are not only good at talking about their areas of expertise but also have excellent public speaking skills. If you need a face for your event, we can provide it for you. </p>
				</div>
		</div>
	</div>
<h1>Follow us!</h1>


<div style="margin-bottom: 50px;">
	<div class="mediaArray">
	<%=image_tag("SCGGnoText.png", alt: "SCGGLogoNoText", id:"SocialLogo") %>
	<div class="row FollowIcon">

		<div class="FollowIcons Twitter col-xs-4">
		<%= link_to "https://twitter.com/SmartCast_GG" do %>
			<i class="fa fa-twitter-square fa-4x"></i>
			<% end %>
		</div>
		<div class="FollowIcons Facebook col-xs-4">
		<%= link_to "https://www.facebook.com/SmartCastGG?fref=ts" do %>
		<i class="fa fa-facebook-square fa-4x"></i>
		<% end %>
		</div>
		<div class="FollowIcons Instagram col-xs-4">
		<%= link_to "https://instagram.com/smartcastgg/" do %>
			<i class="fa fa-instagram fa-4x"></i>
		<% end %>
		</div>
</div>
	</div>

</div>
<!-- </div> -->
</div>


</div>

app/views/users/index.html.erb
Present

app/views/users/personnel.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

app/views/workers/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :twitter%>
      <%= f.text_field :password, class: 'form-control' %>
      <%= f.label :bio %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>  

  </div>
</div>

app/views/workers/index.html.erb
<div class="main">
<h1>Current Staff and Advisors</h1>
<% counter = 0 %> 
<% @worker.each do |w| %>
	<% if counter == 0 %>
		<div class="row">
	<% end %>
	<div class="col-sm-4 worker">
	<%= image_tag w.avatar.url(:thumb) %>
	 <p><%= w.name %></p>
	 <p><%= w.role %></p>
	 </div>
 	<% counter = counter + 1 %>
 	<% if counter == 3 %>
 	<% counter = 0 %>
 		</div>
 	<% end %>
 <% end %>
 	<% if counter != 0 %>
 	</div>
 	<% end %>

 <h1>Contact Us!</h1>
 <div class="contactUsWork">
 Want to work with us? We're always looking for good talent. Send an email to smartcastpr@gmail.com with your CV/Resume and how you'd like to help!
 </div>
</div>

app/views/workers/new.html.erb
<% if logged_in? %>
<% provide(:title, 'Sign up') %>
<h1>Generate Worker</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for( @worker ) do |f| %>
      <p><%= f.label :name %>
      <%= f.text_field :name, style:"color: black;"%></p>

      <p><%= f.label :email %>
      <%= f.email_field :email, style:"color: black;"%></p>

      <p><%= f.label :bio %>
      <%= f.text_field :bio, style:"color: black;"%></p>

      <p><%= f.label :role %>
      <%= f.text_field :role, style:"color: black;" %></p>
      <%= f.file_field :avatar %>
      <%= f.submit "Generate Worker", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= link_to "Log out", logout_path, method: :delete, class: "btn btn-primary" %>

<% end %>

app/views/workers/show.html.erb
<%= @worker.each do |w| %>
	
 <%= w.name %>, <%= w.bio %>

 <%= end %>